In [1]:
# 1. import numpy as np and see the version

import numpy as np
print(np.__version__)

1.21.5


In [30]:
# 2. Create a 1D array of numbers from 0 to 9
array_1 = np.array([0,1,2,3,4,5,6,7,8,9])

In [21]:
# 3. Create a 3×3 numpy boolean array of all True’s
array_2 = np.ones((3,3), dtype=bool)
array_2

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [23]:
# 4. Create a 3x3 boolean array of all False
array_3 = np.zeros((3,3), dtype=bool)
array_3

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [26]:
# 5. Extract all odd numbers from the 1D array
array_1[array_1 % 2 == 1]

array([1, 3, 5, 7, 9])

In [28]:
# 6. Replace all odd numbers in arr with -1 in the 1D array
array_1[array_1 % 2 == 1] = -1
array_1

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [34]:
# 7. Convert a 1D array to a 2D array with 2 rows
array_1.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [88]:
# 8. Create two 2D arrays a and b,
np.random.seed(0)
a = np.random.randint(10, size=(2,3))
b = np.random.randint(10, size=(2,3))
a,b

(array([[5, 0, 3],
        [3, 7, 9]]),
 array([[3, 5, 2],
        [4, 7, 6]]))

In [89]:
# 9. Stack arrays a and b vertically
c = np.vstack((a,b))
c

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6]])

In [90]:
# 10. Stack the arrays a and b horizontally.
d = np.hstack((a,b))
d

array([[5, 0, 3, 3, 5, 2],
       [3, 7, 9, 4, 7, 6]])

In [91]:
# 11. Get the common items between a and b
np.intersect1d(a,b)

array([3, 5, 7])

In [92]:
# 12. From array a remove all items present in array b
a = [item for item in a if item not in b]
a

[array([5, 0, 3])]

In [99]:
# 13. Create a 2d array and Reverse the rows.
np.random.seed(2)
array_2 = np.random.randint(10, size=(3,2))
np.flip(array_2, axis=0)

array([[8, 7],
       [6, 2],
       [8, 8]])

In [100]:
# 14. Reverse the columns
np.flip(array_2, axis=1)

array([[8, 8],
       [2, 6],
       [7, 8]])

In [102]:
# 15. Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.
array_3 = np.random.uniform(5,10, size=(5,3))
array_3

array([[7.52623045, 5.32643252, 7.14061164],
       [5.48265458, 5.63579986, 7.98372654],
       [6.13006   , 5.53472842, 6.10153104],
       [6.74913143, 7.33893742, 6.00871613],
       [8.20203363, 7.41534918, 7.5261836 ]])

In [107]:
# 16. Create a 2d array that print only 3 decimal places
np.round(array_3, 3)

array([[7.526, 5.326, 7.141],
       [5.483, 5.636, 7.984],
       [6.13 , 5.535, 6.102],
       [6.749, 7.339, 6.009],
       [8.202, 7.415, 7.526]])

In [112]:
# 17. Create a 1D array and Limit the number of items printed to a  a maximum of 6 elements.
array_4 = np.arange(10)
np.set_printoptions(threshold = 6)
array_4

array([0, 1, 2, ..., 7, 8, 9])

In [113]:
#18. Import 2 images and convert them to numerical values

<img src="dog-photo[1].png">

In [118]:
from matplotlib.image import imread

In [120]:
doggie = imread('dog-photo[1].png')
doggie

array([[[0.70980394, 0.80784315, 0.88235295, 1.        ],
        [0.72156864, 0.8117647 , 0.8862745 , 1.        ],
        [0.7411765 , 0.8156863 , 0.8862745 , 1.        ],
        ...,
        [0.49803922, 0.6862745 , 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8352941 , 1.        ]],

       [[0.69411767, 0.8039216 , 0.8862745 , 1.        ],
        [0.7019608 , 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49411765, 0.68235296, 0.84313726, 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ]],

       [[0.6901961 , 0.8       , 0.88235295, 1.        ],
        [0.69803923, 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49803922, 0.686274

In [121]:
# 19. Save your file

In [ ]:
# 20. Upload on GitHub and share link